### ISSUE TITLE
Current Status/Tutorial

### ISSUE THREAD

**Issue by tooolbox** [tehnerd/go_keepalived#1]
Hey there,

Was looking around for a Golang alternative to keepalived (which I found as a simpler alternative to Pacemaker) and found this!

I can't say that I'm familiar enough yet with all this cluster stuff to fully track with your code.  Is this stuff production-ready enough to perform flip-flops between active and passive servers?  Bit of a tutorial would be awesome  :)

Thanks!

**Comment by tehnerd** [comment]
Morning,
 i'm afraid that i'm not actively working  on this one right now (and it has some known issues). So i'd recomend you to look into github.com/kobolog/gorb or github.com/google/seesaw/. both of em are doing the same work (they are go-based lb/healthchecking solution which use ipvs for load balancing). as far as i know gorb has better docker's integration if this is the case.

**Comment by tooolbox** [comment]
Righto, thanks!
